# server:
#   # Run HTTP instead of HTTPS â€“ Istio will do TLS
#   extraArgs:
#     - --insecure
#   server: 
#     insecure: true
#   ingress:
#     enabled: true
#   service:
#     type: ClusterIP
#     port: 80

# configs:
#   cm:
#     application.namespaces: argocd, bootstrap
    #url: https://argocd.local